global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8000']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8081']

  - job_name: 'cdc-worker'
    static_configs:
      - targets: ['cdc-worker:8082']